gnuradio/newsched

blocklib/blocks/lib/multiply_const_blk.cpp
schedulers/simplestream/include/gnuradio/schedulers/simplestream/scheduler_simplestream.hpp

Similar to parameter_change, but handle and block on the return value coming back

add parameter query mechanism

---

CMakeLists.txt
pmt/CMakeLists.txt
pmt/include/pmt/CMakeLists.txt
pmt/include/pmt/pmt.hpp
pmt/lib/CMakeLists.txt
pmt/lib/pmt.cpp
pmt/test/CMakeLists.txt
pmt/test/qa_pmt.cpp
pmt/test/test_pmt.cpp

Still need thought on how to handle serialization (flatbuffers?) but for now get something functional and simple to use as a placeholder for pmt

pmt: add pmt structure based on std::any

---

blocklib/blocks/include/gnuradio/blocklib/blocks/nop_source.hpp
runtime/include/gnuradio/domain_adapter.hpp
runtime/include/gnuradio/edge.hpp
runtime/include/gnuradio/flat_graph.hpp
runtime/include/gnuradio/graph.hpp
runtime/lib/edge.cpp
runtime/lib/flat_graph.cpp
runtime/lib/graph.cpp
runtime/lib/graph_utils.cpp
schedulers/mt/bench/bm_copy.cpp
schedulers/mt/bench/bm_fanout.cpp
schedulers/mt/bench/bm_nop.cpp
schedulers/mt/include/gnuradio/schedulers/mt/scheduler_mt.hpp
schedulers/mt/test/qa_block_grouping.cpp
schedulers/mt/test/qa_scheduler_mt.cpp
schedulers/st/bench/bm_copy.cpp
schedulers/st/bench/bm_fanout.cpp
schedulers/st/include/gnuradio/schedulers/st/buffer_management.hpp
schedulers/st/lib/buffer_management.cpp
schedulers/st/test/qa_scheduler_st.cpp
schedulers/st/test/test_buffers.cpp

also allow for the api
connect(a,b)->set_custom_buffer(buffer_properties)

Cleanup the custom buffers api a bit

---

blocklib/cuda/include/gnuradio/blocklib/cuda/copy.hpp
blocklib/cuda/lib/copy.cpp
blocklib/cuda/lib/copy.cu
runtime/include/gnuradio/cudabuffer.hpp
runtime/lib/cudabuffer.cu
schedulers/mt/bench/cuda/bm_copy.cpp

use cuda streams for blocks and buffers
Also, add a load parameter to the copy function to simulate longer kernel execution time

cuda: add streams to cuda blocks and buffers

---

runtime/include/gnuradio/port.hpp
runtime/include/gnuradio/thread.hpp
runtime/lib/meson.build
runtime/lib/thread.cpp
schedulers/mt/bench/bm_copy.cpp
schedulers/mt/include/gnuradio/schedulers/mt/block_group_properties.hpp
schedulers/mt/include/gnuradio/schedulers/mt/scheduler_mt.hpp
schedulers/mt/include/gnuradio/schedulers/mt/thread_wrapper.hpp
schedulers/mt/lib/scheduler_mt.cpp
schedulers/mt/lib/thread_wrapper.cpp

Integrated code from GR to set CPU affinity for more consistent benchmarking

Add CPU affinity functionality

---

blocklib/blocks/include/gnuradio/blocklib/blocks/annotator.hpp
blocklib/blocks/include/gnuradio/blocklib/blocks/copy.hpp
blocklib/blocks/include/gnuradio/blocklib/blocks/fanout.hpp
blocklib/blocks/include/gnuradio/blocklib/blocks/head.hpp
blocklib/blocks/include/gnuradio/blocklib/blocks/nop.hpp
blocklib/blocks/include/gnuradio/blocklib/blocks/nop_head.hpp
blocklib/blocks/include/gnuradio/blocklib/blocks/nop_source.hpp
blocklib/blocks/include/gnuradio/blocklib/blocks/null_source.hpp
blocklib/blocks/lib/annotator.cpp
blocklib/blocks/lib/meson.build
blocklib/blocks/lib/multiply_const.cpp
blocklib/blocks/lib/vector_sink.cpp
blocklib/blocks/lib/vector_source.cpp
blocklib/cuda/lib/copy.cpp
blocklib/cuda/lib/multiply_const.cpp
pmt/include/pmt/pmtf.hpp
runtime/include/gnuradio/block_work_io.hpp
runtime/include/gnuradio/buffer.hpp
runtime/include/gnuradio/flowgraph.hpp
runtime/include/gnuradio/simplebuffer.hpp
runtime/include/gnuradio/tag.hpp
runtime/include/gnuradio/vmcircbuf.hpp
runtime/lib/edge.cpp
runtime/lib/flowgraph.cpp
runtime/lib/vmcircbuf.cpp
schedulers/mt/lib/graph_executor.cpp
schedulers/mt/test/meson.build
schedulers/mt/test/qa_tags.cpp

Uses buffer object pointer in block work functions
Makes tags use PMTs (instead of the previous stand-in strings)
Tag propagation and handling
Tag QA tests
Still probably need more functionality/safeguards, but wanted to get tags up to a basic level of functionality

Tags and Tag Handling

---

runtime/include/gnuradio/block_work_io.hpp
runtime/include/gnuradio/buffer.hpp
runtime/include/gnuradio/cudabuffer.hpp
runtime/include/gnuradio/cudabuffer_pinned.hpp
runtime/include/gnuradio/domain_adapter.hpp
runtime/include/gnuradio/simplebuffer.hpp
runtime/include/gnuradio/vmcircbuf.hpp
runtime/lib/buffer.cpp
runtime/lib/cudabuffer.cu
runtime/lib/cudabuffer_pinned.cu
runtime/lib/meson.build
runtime/lib/simplebuffer.cpp
runtime/lib/vmcircbuf.cpp
schedulers/mt/bench/bm_copy.cpp
schedulers/mt/bench/bm_fanout.cpp
schedulers/mt/bench/bm_nop.cpp
schedulers/mt/bench/cuda/bm_copy.cpp
schedulers/mt/include/gnuradio/schedulers/mt/buffer_management.hpp
schedulers/mt/lib/buffer_management.cpp
schedulers/mt/lib/graph_executor.cpp
schedulers/mt/test/cuda/qa_scheduler_mt_cuda_copy.cpp
schedulers/mt/test/qa_block_grouping.cpp
schedulers/mt/test/qa_scheduler_mt.cpp
schedulers/mt/test/qa_tags.cpp

This adds buffer readers rather than a buffer for every edge.  Every edge is associated with a buffer, but only one buffer is created per output port and an a reader is assigned per input port.

Buffer readers

---

runtime/include/gnuradio/buffer.hpp
runtime/include/gnuradio/buffer_management.hpp
runtime/include/gnuradio/cudabuffer.hpp
runtime/include/gnuradio/cudabuffer_pinned.hpp
runtime/include/gnuradio/edge.hpp
runtime/include/gnuradio/flat_graph.hpp
runtime/include/gnuradio/node.hpp
runtime/include/gnuradio/scheduler.hpp
runtime/include/gnuradio/vmcircbuf.hpp
runtime/lib/buffer_management.cpp
runtime/lib/cudabuffer.cu
runtime/lib/edge.cpp
runtime/lib/graph.cpp
runtime/lib/graph_utils.cpp
runtime/lib/meson.build
runtime/lib/vmcircbuf.cpp
schedulers/mt/include/gnuradio/schedulers/mt/scheduler_mt.hpp
schedulers/mt/lib/scheduler_mt.cpp
schedulers/mt/test/cuda/qa_scheduler_mt_cuda_copy.cpp
schedulers/mt/test/qa_scheduler_mt.cpp

Clean up the interface to the custom buffers
Add min/max and requested sizes to the buffer (as opposed to the block)

Custom buffer cleanup

---

.gitignore
runtime/include/gnuradio/block_group_properties.hpp
runtime/include/gnuradio/buffer.hpp
runtime/include/gnuradio/buffer_sm.hpp
runtime/lib/buffer.cpp
runtime/lib/buffer_sm.cpp
runtime/lib/meson.build
schedulers/mt/lib/graph_executor.cpp
schedulers/mt/lib/thread_wrapper.cpp
schedulers/mt/test/meson.build
schedulers/mt/test/qa_scheduler_mt.cpp
schedulers/mt/test/qa_single_mapped_buffers.cpp

Adds the CPU version of single mapped buffers
QA still fails sometimes which needs to be investigated
Signed-off-by: Josh Morman <jmorman@perspectalabs.com>

runtime: add single mapped buffers

---

blocklib/filter/meson.build
blocklib/filter/moving_average/meson.build
blocklib/filter/moving_average/moving_average.yml
blocklib/filter/moving_average/moving_average_cpu.cc
blocklib/filter/moving_average/moving_average_cpu.hh
blocklib/filter/test/meson.build
blocklib/filter/test/qa_moving_average.py
blocklib/math/complex_to_mag/complex_to_mag_cpu.hh
blocklib/math/complex_to_mag_squared/complex_to_mag_squared_cpu.hh
blocklib/math/divide/divide_cpu.cc
blocklib/math/multiply/multiply_cpu.cc
utils/blockbuilder/templates/blockname_templated.hh.j2

Can prevent the extra copy by not consuming all the input samples, but wanted to mimic original functionality to start
Signed-off-by: Josh Morman <jmorman@perspectalabs.com>

filter: moving average with no history

---

blocklib/create_block.py
blocklib/create_mod.py
blocklib/newblock/meson.build
blocklib/newblock/newblock.yml
blocklib/newblock/newblock_cpu.cc
blocklib/newblock/newblock_cpu.hh
blocklib/newblock/newblock_cpu_t.cc
blocklib/newblock/newblock_cpu_t.hh
blocklib/newblock/newblock_cuda.cc
blocklib/newblock/newblock_cuda.cu
blocklib/newblock/newblock_cuda.cuh
blocklib/newblock/newblock_cuda.hh
blocklib/newblock/newblock_cuda_t.cc
blocklib/newblock/newblock_cuda_t.cu
blocklib/newblock/newblock_cuda_t.cuh
blocklib/newblock/newblock_cuda_t.hh
blocklib/newblock/newblock_t.yml
blocklib/newmod/include/gnuradio/newmod/meson.build
blocklib/newmod/lib/meson.build
blocklib/newmod/meson.build
blocklib/newmod/python/newmod/__init__.py
blocklib/newmod/python/newmod/meson.build
blocklib/newmod/test/meson.build
python/newsched/__init__.py

Python script to create new module within blocklib using template newmod directory.

create_mod script

---

blocklib/qtgui/lib/meson.build
blocklib/qtgui/meson.build
blocklib/qtgui/test/qttest.py
blocklib/qtgui/time_sink/time_sink.yml
blocklib/qtgui/time_sink/time_sink_cpu.cc
blocklib/qtgui/time_sink/time_sink_cpu.hh
meson.build
meson_options.txt
python/newsched/__init__.py
runtime/include/gnuradio/block_work_io.hh
utils/blockbuilder/templates/blockname_pybind_templated.cc.j2

Mainly testing out the block generation to see what changes are needed to support something as funky as qtgui
Still much work to do to have a fully functional qtgui block (started with time sink), but this is enough to have a basic plot with the default plotting parameters.  
Wonky things:
- metaclass conflict between gr.flowgraph and Qt 
- special binding for .qwidget means putting lambda method in yml (hacky)

Minimal qtgui

---

README.md

Signed-off-by: David Sorber <david.sorber@blacklynx.tech>

documentation: Adding full Ubuntu 20.04 build example to README

---

.gitignore
CHANGELOG.md
meson.build

Update CHANGELOG and version for 0.1.0

---

runtime/lib/flowgraph.cc
schedulers/nbt/lib/meson.build
schedulers/nbt/lib/scheduler_nbt.cc

runtime/scheduler: generic factory interface

---

blocklib/soapy/lib/block_impl.cc
runtime/lib/buffer_cpu_vmcirc_mmap_shm_open.cc
runtime/lib/buffer_cuda.cu
runtime/lib/buffer_cuda_sm.cu
runtime/lib/flat_graph.cc
runtime/lib/thread.cc
schedulers/nbt/lib/thread_wrapper.cc

global: removal of boost::format

---

blocklib/blocks/annotator/annotator.yml
blocklib/blocks/copy/copy.yml
blocklib/blocks/delay/delay.yml
blocklib/blocks/head/head.yml
blocklib/blocks/load/load.yml
blocklib/blocks/nop/nop.yml
blocklib/blocks/nop_head/nop_head.yml
blocklib/blocks/nop_source/nop_source.yml
blocklib/blocks/null_sink/null_sink.yml
blocklib/blocks/null_source/null_source.yml
blocklib/blocks/throttle/throttle.yml
blocklib/streamops/stream_to_streams/stream_to_streams.yml
utils/blockbuilder/templates/blockname.grc.j2
utils/modtool/newblock/newblock.yml

grc/blocklib: add default cmd port

---

blocklib/blocks/throttle/throttle_cpu.cc
schedulers/nbt/include/gnuradio/schedulers/nbt/thread_wrapper.hh
schedulers/nbt/lib/graph_executor.cc
schedulers/nbt/lib/thread_wrapper.cc
schedulers/nbt/test/cuda/qa_scheduler_nbt_cuda_copy.cc

Prevent kicking the queue too often - clean up some QA

---

.gitmodules
meson.build
schedulers/nbt/bench/bm_copy.cc
schedulers/nbt/bench/bm_fanout.cc
schedulers/nbt/bench/bm_nop.cc
schedulers/nbt/bench/cuda/bm_copy.cc
schedulers/nbt/bench/meson.build

scheduler/nbt: remove boost program options

---

schedulers/nbt/test/meson.build
schedulers/nbt/test/qa_python_block.py

qa: update python block tests with updated api

---

blocklib/blocks/msg_forward/msg_forward.yml
blocklib/blocks/msg_forward/msg_forward_cpu.cc
blocklib/blocks/msg_forward/msg_forward_cpu.hh
runtime/include/gnuradio/block.hh
runtime/include/gnuradio/concurrent_queue.hh
runtime/include/gnuradio/executor.hh
runtime/include/gnuradio/node.hh
runtime/include/gnuradio/port.hh
runtime/lib/block.cc
runtime/lib/flowgraph_monitor.cc
schedulers/nbt/bench/bm_msg_forward.cc
schedulers/nbt/bench/meson.build
schedulers/nbt/include/gnuradio/schedulers/nbt/thread_wrapper.hh
schedulers/nbt/lib/graph_executor.cc
schedulers/nbt/lib/thread_wrapper.cc

runtime/sched: flowgraph execution msg block aware

---

blocklib/fft/lib/fftw_fft.cc
blocklib/qtgui/include/gnuradio/qtgui/qtgui_types.h
gr/include/gnuradio/file_lock.h
gr/include/gnuradio/high_res_timer.h
gr/include/gnuradio/symbol_location.h
gr/lib/constants.cc.in
meson.build

Removes posix_time and dll:line_location

More boost removal

---

blocklib/blocks/vector_sink/vector_sink.yml
blocklib/blocks/vector_source/vector_source.yml
blocklib/fft/fft/fft.yml
blocklib/math/add/add.yml
blocklib/math/complex_to_mag/complex_to_mag.yml
blocklib/math/complex_to_mag_squared/complex_to_mag_squared.yml
blocklib/math/divide/divide.yml
blocklib/math/multiply/multiply.yml
blocklib/math/multiply_const/multiply_const.yml
blocklib/streamops/interleaved_short_to_complex/interleaved_short_to_complex.yml
gr/include/gnuradio/port.h
gr/lib/port.cc
gr/python/gr/bindings/port_pybind.cc
gr/python/gr/gateway_cupy.py
gr/python/gr/gateway_numpy.py
gr/python/gr/numpy_helpers.py
test/cuda/qa_python_block_cuda.py
test/qa_python_block.py
utils/blockbuilder/templates/blockname.grc.j2
utils/blockbuilder/templates/macros.j2
utils/modtool/newblock/newblock_t.yml

gr: rename dims to shape

---

gr/include/gnuradio/flat_graph.h
gr/include/gnuradio/graph.h
gr/include/gnuradio/hier_block.h
gr/lib/flowgraph.cc
gr/python/gr/bindings/gr_pybind.cc
gr/python/gr/bindings/hier_block_pybind.cc
gr/python/gr/bindings/meson.build
test/meson.build
test/qa_hier_block.py

gr: hier_block basic support

---

blocklib/filter/fir_filter/.gitignore
blocklib/filter/fir_filter/fir_filter.yml
blocklib/filter/fir_filter/fir_filter_cpu.cc
blocklib/filter/fir_filter/fir_filter_cpu.h
blocklib/filter/test/qa_fir_filter.py
blocklib/streamops/keep_m_in_n/.gitignore
blocklib/streamops/keep_m_in_n/keep_m_in_n.yml
blocklib/streamops/keep_m_in_n/keep_m_in_n_cpu.cc
blocklib/streamops/keep_m_in_n/keep_m_in_n_cpu.h
blocklib/streamops/keep_m_in_n/keep_m_in_n_cuda.cc
blocklib/streamops/keep_m_in_n/keep_m_in_n_cuda.h
blocklib/streamops/probe_signal/.gitignore
blocklib/streamops/probe_signal/probe_signal.yml
blocklib/streamops/probe_signal/probe_signal_cpu.cc
blocklib/streamops/probe_signal/probe_signal_cpu.h
blocklib/streamops/probe_signal_v/.gitignore
blocklib/streamops/probe_signal_v/probe_signal_v.yml
blocklib/streamops/probe_signal_v/probe_signal_v_cpu.cc
blocklib/streamops/probe_signal_v/probe_signal_v_cpu.h
blocklib/streamops/test/meson.build
blocklib/streamops/test/qa_keep_m_in_n.py
blocklib/streamops/test/qa_probe_signal.py
utils/blockbuilder/templates/blockname.grc.j2
utils/blockbuilder/templates/blockname_impl_gen.h.j2
utils/blockbuilder/templates/blockname_pybind_templated.cc.j2
utils/blockbuilder/templates/blockname_templated.cc.j2
utils/blockbuilder/templates/blockname_templated.h.j2

keep_m_in_n
probe_signal
probe_signal_v
fir_filter
and associated template and gr changes

More blocks

---

gr/include/gnuradio/flowgraph.h
gr/include/gnuradio/runtime.h
gr/include/gnuradio/scheduler.h
gr/lib/flowgraph.cc
gr/lib/runtime.cc
gr/python/gr/bindings/flowgraph_pybind.cc
gr/python/gr/bindings/runtime_pybind.cc
grc/core/FlowGraph.py
grc/core/generator/flow_graph.py.mako
schedulers/nbt/include/gnuradio/schedulers/nbt/scheduler_nbt.h
schedulers/nbt/include/gnuradio/schedulers/nbt/thread_wrapper.h
schedulers/nbt/lib/scheduler_nbt.cc
schedulers/nbt/lib/thread_wrapper.cc

gr/schedulers: allow ctrl-c from python

---

blocklib/fileio/file_source/file_source_cpu.cc
blocklib/streamops/annotator/annotator_cpu.cc
gr/include/gnuradio/hier_block.h
subprojects/pmt.wrap

pmt: update pointer to latest and minor changes

---

blocklib/analog/fm_deemph/fm_deemph_cpu.cc
blocklib/analog/test/qa_quadrature_demod.py
blocklib/filter/test/qa_iir_filter.py
blocklib/streamops/throttle/throttle_cpu.cc
blocklib/streamops/throttle/throttle_cpu.h
gr/include/gnuradio/block.h
gr/include/gnuradio/hier_block.h
gr/lib/block.cc
gr/lib/graph.cc

small changes in tutorial preparation

---

bench/cuda/bm_copy.cc
blocklib/filter/bench/bm_pfb_channelizer.py
blocklib/streamops/load/load.yml
blocklib/streamops/load/load_cuda.cc
blocklib/streamops/load/load_cuda.cu
blocklib/streamops/load/load_cuda.cuh
blocklib/streamops/load/load_cuda.h
gr/include/gnuradio/block.h
gr/include/gnuradio/concurrent_queue.h
gr/include/gnuradio/flat_graph.h
gr/include/gnuradio/hier_block.h
gr/include/gnuradio/port.h
gr/include/gnuradio/scheduler_message.h
gr/lib/block.cc
gr/lib/port.cc
schedulers/nbt/lib/graph_executor.cc
schedulers/nbt/lib/thread_wrapper.cc
test/qa_hier_block.py
utils/blockbuilder/schema/gnuradio-block.json
utils/blockbuilder/templates/blockname.cc.j2
utils/blockbuilder/templates/blockname_pybind.cc.j2
utils/blockbuilder/templates/blockname_pyshell.h.j2
utils/blockbuilder/templates/blockname_templated.cc.j2

There were some significant weaknesses with hier blocks that are addressed here.
Probably need to break this up into multiple PRs, as there is some other custom buffer profiling work that made its way in here

Hier Blocks and other various updates
